PR: Minor changes, add refreshrate, extendable volume dialog (#3)
* frameworks: Add unlinked ringtone and notification volumes

Port over linked volumes from 12.1

Implement linked volumes and add upgrade path.

Change-Id: Ibbeff656fcaaa4a2ff79de530b48b216df271b21

frameworks: read VOLUME_LINK_NOTIFICATION from proper table

Change-Id: I15e9caa18f307a51a732c7a59013bbbb234a7477
Signed-off-by: Roman Birg <roman@cyngn.com>
(cherry picked from commit 1b7cfa1716017e0d03c9693428c21d8e11c5dc0a)

fix Notification volume slider linking

Change-Id: I0f74485f5c8c2aa7698cf9ba1c60c2c8c967798d
Signed-off-by: Roman Birg <roman@cyngn.com>

Improve SeekBarVolumizer behavior with unlinked streams

- Fix notification stream enabling at 0 volume
- Fix the notification slider being set when moving ringer stream

Change-Id: If3705cc833c07f726f8ad7b1ec79a42e86e8ff22
Signed-off-by: Roman Birg <roman@cyngn.com>

base: Fix notification sounds for wifi only devices

The linking of voice & notification doesn't take into account the
fact that a device may not actually have voice capabilities.  Whenever
checking whether or not to link notification and ring volumes, also
verify that the device really is voice capable.

Change-Id: Iae49302d3b5934d36b182e289e4975f5dd85b834

frameworks: fix setting up linked notification stream on boot

updateStreamVolumeAlias() was previously responsible for checking the
linked notification variable and mapping the notification stream, but
the setting to read whether the notifications were linked was read in
after that method had run which was responsible for linking them.
Extract the logic and re-run it again after reading the persisted
settings.

Change-Id: Ia62bf3ca072def54ec6ebf4f9e865d9c913e3bc4
Signed-off-by: Roman Birg <roman@cyngn.com>

fixup volume stream linking

- Make the SeekBarVolumizer move notification and ringer streams when
 linked and moving ringer.

- Fix initial state causing volume stream seek bar to be set to 0
  initially

- Clean up AudioService initialization code

Change-Id: Ia11a7a392e5eb3ef862147843e365d5f20eaf90a
Signed-off-by: Roman Birg <roman@cyngn.com>

SystemUI: Fix volume panel inconsistencies

* Use xml drawables everywhere
* Add muted notification icon
* Use AOSP naming scheme for drawables

Change-Id: I14a3af9a7aecf4828f81a8e39855608e452848d6

Misc fixes

Change-Id: Ia94b0a6655e52f5949f031360f525c871cd8df14
Signed-off-by: Meninblack007 <sanyam.53jain@gmail.com>

Use STREAM_RING on non-voice capable devices

* That's what Google does.

Change-Id: Iac88d161eb1dccbbb5c538d5e04d8d1fc43edef2
(cherry picked from commit 981e89eb6b99c058a9b3bf533e6494ab44a4b241)

VolumeDialog: Fix mismerge

Fixes not disappearing cast pickers

* Commit 568585b introduced a new LinearLayout for the volume rows
* Remove unused booleans

Change-Id: I0660d10872cc1098fdd67b618a20ea0f8e926e68

Fix VOLUME_LINK_NOTIFICATION javadoc

* Fixes checkapi:
  frameworks/base/core/java/android/provider/Settings.java:8920: error:
  Added field android.provider.Settings.Secure.VOLUME_LINK_NOTIFICATION [AddedField]

Change-Id: I4da34de53ce23e90d5f2eff72ef0a15034f08ec1

Change-Id: I7695aa15bc85e8ff19747ba7cd6700e190c7d988

* SystemUI: runtime configurable audio panel location

* Updates for twelve (bgcngm / Arian)
  * Adapt to new UI

* Updates for eleven (LuK1337):
  * Disable on TVs
  * Simplify changes once again.

* Updates for ten (sam3000):
  * Squash in tuner service settings reset blacklist.
  * Remove layout xml changes that aren't needed.
  * Apply slide in/out animations to landscape too
    (they work fine).
  * Few other simplifications.

* Placement is now determined at runtime by a lineage setting.
  Use TunerService to track settings change.
  Various cleanup and fix formatting.
  Fixed left/right gravity on expand arrow and ringer.
  Fix commit author.
  (sam3000)

This is a squashed and adapted commit of the following patches:

----

  From cf187bd54fbd807e16b0ac3593e839008efd302e Mon Sep 17 00:00:00 2001
  From: "a.derendyaev" <a.derendyaev@magdv.com>
  Date: Wed, 19 Dec 2018 21:57:45 +0800
  Subject: [PATCH] SystemUI: allow devices override audio panel location

  Some devices have volume buttons on left side and it not fancy if volume panel will be at right side.
  You can override panel location using overlay for SystemUI:

  <!-- Allow devices override audio panel location to the left side -->
  <bool name="config_audioPanelOnLeftSide">true</bool>

  Change-Id: I8a2302867010b0e6a02efa68df57e534ce7bbf46
  Signed-off-by: Jagrav Naik <jagravnaik0@gmail.com>
  Signed-off-by: Anirudh Gupta <anirudhgupta109@gmail.com>

----

  From 9d0ff1efd26961a4f14d0821f50ebe80c2a65ff9 Mon Sep 17 00:00:00 2001
  From: Alex Cruz <alex@dirtyunicorns.com>
  Date: Fri, 21 Dec 2018 22:08:52 -0600
  Subject: [PATCH] Volume panel: Do the same with less

  Use common volume_dialog layout for both left- and right-aligned panel

  [@TheDorkKnightRises - POSP]
  - Tweak padding values to make them uniform across both alignments
  - Remove redundant comment

  Change-Id: If41456f71ffd18466166e7b4120ff34d9e6f5a46
  Signed-off-by: Josh Fox (XlxFoXxlX) <joshfox87@gmail.com>

----

Author: Sam Mortimer <sam@mortimer.me.uk>
Date:   Sun Jun 9 13:33:05 2019 -0700

    SystemUI: Blacklist volume panel on left setting from tuner reset

    Change-Id: I47ddb3b818cfa3548fef42fa686d0991e2a35605

Author: programminghoch10 <hoch10@kabelbw.de>
Date:   Mon Jul 12 17:55:28 2021 +0200

    SystemUI: VolumeDialogImpl: Fix volume panel permanently visible

    * The Volume Panel is permanently visible when changing the panel side while the panel is open until SystemUI is restarted
    * This change removes the Panel View when changing the panel side

    Fixes: https://gitlab.com/LineageOS/issues/android/-/issues/3482

    Change-Id: Ic3ca5a196315e96024121c995cc6282fb74f6e4c

[cjh1249131356]: Convert TunerService to SettingsObserver

Change-Id: If22c97eb1ce4cfb13396d182d90786f4b7acaee7

* VolumePanel: Add long click for expand icon

Signed-off-by: AnierinB <anierin@evolution-x.org>

* VolumeDialogImpl: Respect multiple visible rows in landscape

If the user is in a call we are showing two volume rows, the default
(music) stream and the active stream, in this case the voice call.
Currently the second row is not touchable in landscape mode because
the calculation of the touchable region does not handle the case of
multiple visible rows.

This patchset adds a check wether the ringer drawer extra size is bigger
than the additionally visible rows and then substracts the size of the
visible rows so that they stay touchable.

Test: While receiving a call in landscape both, the music row and the
      ring row, are touchable. Touches at the left of the volume panel
      are still going through the app behind the volume panel.
Change-Id: Icda80b7a98d5510747bc92ef12a3c7647131b18d

* VolumeDialogImpl: Don't hide the default stream when adjusting the music stream

If there are two visible rows and the user touches the default (music)
row, the other row disappears immediately. Avoid this behaviour by
tracking the row with which this panel was created and keep showing
that row if the user adjusts the music stream.

Test: While receiving a call both rows are touchable and the additional
      row does not disappear when adjusting the music stream.
Change-Id: I4e14a0ea50c5cc41cb279c6fbfc8a7d6e6d1ba61

* VolumeDialogImpl: Fix cuttered layout when on setup or lock task mode

Change-Id: I20aacbda4e1a90cad3120ed6f4a65c8c884521cf

* SystemUI: Make the volume dialog expandable

Change-Id: I282aece97f0c7b4435c94ca773631e2d9e738a14

* SystemUI: VolumeDialogImpl: Fix inactive rows tint

* on some shades like peach/pink ,the inactive row is quite identical to the active row's tint on dark mode. We might wight to use a1 shades and modified coloraccentprimary to fix this issue.

Signed-off-by: strwbrry143 <alexfinhart@gmail.com>

* SystemUI: VolumeDialogImpl: Change bg tint for inactive rows

The secondary accent in light mode does not have a good contrast
to the previously white icon.

Previously: https://imgur.com/a/XHpDHDJ
Now: https://imgur.com/a/QCk3QwC

Change-Id: Ib61ad4803e0e3c6cc9163408137c7a16742922b6

* SystemUI: Show notification row when it's unlinked to ringer volume

Signed-off-by: Mesquita <mesquita@aospa.co>
Change-Id: Id7a2602153dbc94eb40caf70946d2b31e4a3c19f

SystemUI: Show notification row only when unlinked

("SystemUI: Show notification row when it's unliked to ringer volume")
caused notification row to show in expanded volume panel
even when notification and ring volumes are linked. Fix
it so that it shows only when they are unlinked.

Change-Id: I1d4768974c07247bae38470260f7917da44bd911
Co-authored-by: Adithya R <gh0strider.2k18.reborn@gmail.com>

* VolumeDialog: notifyVisible after the volume panel is fully hidden

notifyVisible(false) leads to reset of active stream. As a result,
the current active row will be untinted. Currently, this happens
immediately after the dismissal is requested, before the volume panel
is fully hidden.

User can notice the row has been untinted before the panel is hidden.

This changes moves notifyVisible to the end of animation so the volume
panel appearance will be consistent in between.

Change-Id: Iacd83d48634a11bc248c9a2a45b68b53256fdcb2
Signed-off-by: Jesse Chan <jc@lineageos.org>

* VolumeDialog: Display default row when active row is notification

Commit "frameworks: Add unlinked ringtone and notification volumes"
introduced STREAM_NOTIFICATION. However, this stream type, although
marked as important, was not added to the list in shouldBeVisibleH.
As a result, the volume panel behavior of STREAM_NOTIFICATION deviates
from other user-facing streams like media, call and ring.

This change adds STREAM_NOTIFICATION so the behavior becomes consistent.

Change-Id: I092c5bf0ae8cbee85af6adfa0da308dfdb60e66a
Signed-off-by: Jesse Chan <jc@lineageos.org>

* SystemUI: Avoid NPE in volume dialog

Change-Id: I1bc6d46de01ddd4db6b32555e5557611550d007e

* SystemUI: Allow Wi-Fi/cell tiles to co-exist with provider model

The dedicated Wi-Fi/cellular data QS tiles are partially working now
that we've exposed them in the list of tile options, but they're very
buggy and somewhat broken when the provider model (unified internet) is
enabled.

Allow the tiles to co-exist with InternetTile and the provider model
(including both settings_provider_model and combined signal icons) by
always including QS icons in Wi-Fi/data indicator callbacks, and add
a new flag to indicate whether they should be shown in the internet
tile.

(cdesai, mkbestas: Port to 12L)

Change-Id: I10af134b35dfabdb9275f1aca8ca8512e1db6d27
Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>

* base: Allow setting preferred refresh rate [1/2]

 * also register missing content observer for peak refresh
   rate while we're at it

Change-Id: I4f494687cef87dc9b24f4c712a8dbdedf1def400
Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>

Signed-off-by: AnierinB <anierin@evolution-x.org>
Signed-off-by: strwbrry143 <alexfinhart@gmail.com>
Signed-off-by: Jesse Chan <jc@lineageos.org>
Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
Co-authored-by: Adnan Begovic <adnan@cyngn.com>
Co-authored-by: a.derendyaev <a.derendyaev@magdv.com>
Co-authored-by: ProchyGaming <dominikprochazka100@gmail.com>
Co-authored-by: Arian <arian.kulmer@web.de>
Co-authored-by: jhenrique09 <jhsv09@gmail.com>
Co-authored-by: strwbrry143 <alexfinhart@gmail.com>
Co-authored-by: Mesquita <mesquita@aospa.co>
Co-authored-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
Co-authored-by: Jesse Chan <jc@lineageos.org>
Co-authored-by: Christian Hoffmann <chrmhoffmann@gmail.com>
Co-authored-by: Danny Lin <danny@kdrag0n.dev>